NeuroID/NIDEvent.swift
NeuroID/NeuroIDTracker.swift

Fixing event structure for register targets, window load events and text input events.

reg target fix, stop fix

---

.github/workflows/github-actions-ios.yml
NeuroID.xcodeproj/project.pbxproj
NeuroID/DataStore.swift
NeuroID/NIDEvent.swift
NeuroID/NeuroIDSensors.swift
NeuroID/NeuroIDTracker.swift
SDKTest/SensorsTest.swift

Create Class for sensor manager and some access methods
Create Enum with sensor types
Create Struct to save information
Tickets: [ENG-2568 , ENG-25670,  ENG-25678]

Implement Sensor Manager

---

.github/workflows/github-actions-ios.yml
@
NeuroID/DataStore.swift
NeuroID/NIDEvent.swift
NeuroID/NeuroIDTracker.swift
Podfile
Podfile.lock
SDKTest/PayloadTest.swift

- Adding required entities for the neuroid event
- Adding new validator
- New  parameter

Adding new json validator

---

Neuro-ID.podspec
NeuroID.xcodeproj/project.pbxproj
NeuroID/NIDMetadata.swift

Adding a class that contain all the public information

Adding Metadata class to project

---

NeuroID/NIDEvent.swift
NeuroID/NeuroIDTracker.swift

- Change Attr to array and as a unique entity

Custom Atrr as Array

---

NeuroID/NIDEvent.swift
NeuroID/NeuroIDSensors.swift
NeuroID/NeuroIDTracker.swift

Modificed atrr for tg
Modifed attrs (adding to struct)

updating attributes

---

NeuroID/NeuroIDTracker.swift
SDKTest/EventTests.swift

- setscreen name unit test fix
- New paste function

Hot fix Changes

---

Neuro-ID.podspec
NeuroID/NeuroIDTracker.swift
SDKTest/Info.plist

Update Marketing Version and podspec
Erease doble paste call for the simulator

New version 2.3.0

---

NeuroID/NeuroIDTracker.swift

Reverts Neuro-ID/neuroid-ios-sdk#64

Revert "Eng 3886 implement new register target"

---

.github/workflows/github-actions-ios.yml
.github/workflows/github-actions-version-check.yml

[ENG-3954] - update the name

---

NeuroID/NeuroIDTracker.swift

call native functions before the stop verification

[ENG-3959] - Call Native function

---

LICENSE

This PR creates a LICENSE file for the iOS SDK.
- New file (non-breaking change)
[ENG-5714]: https://neuro-id.atlassian.net/browse/ENG-5714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-5714 add MIT License file

---

.github/workflows/github-actions-ios-staging.yml
.github/workflows/github-actions-ios.yml

NOTE: This is the same update as the previous PR but targeting Dev to kick off the workflow

ENG-5826 - Use new service account PAT

---

.github/workflows/test-sdk.yml

[ENG-6006]
[ENG-6006]: https://neuro-id.atlassian.net/browse/ENG-6006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6006] Update PR testing

---

NeuroID/NIDMetadata.swift
NeuroID/TrackerClassExtensions/UIClassExtensions/CommonTextFieldUtils.swift
NeuroID/TrackerClassExtensions/UIClassExtensions/UITextField.swift
NeuroID/TrackerClassExtensions/UIClassExtensions/UITextView.swift
NeuroID/TrackerEvents/TextControlEvents.swift

[ENG-6061]
[ENG-6061]: https://neuro-id.atlassian.net/browse/ENG-6061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6061] Removing secure text

---

NeuroID/NIDMetadata.swift
SDKTest/UIViewExtensionTests.swift

ENG-6368/volume key

---

NeuroID/DataStore.swift
NeuroID/NeuroIDClass/Extensions/NIDUser.swift
NeuroID/NeuroIDClass/NeuroID.swift
SDKTest/DataStoreTests.swift
SDKTest/NeuroIDClassTests.swift

Additionally - Removed where we were storing the UserID in the UserDefaults because it should not be a long lasting variable, memory only

ENG-6161 - Add Queued Events Store

---

NeuroID.xcodeproj/project.pbxproj
NeuroID/NIDEvent.swift
NeuroID/NeuroIDClass/Extensions/NIDRN.swift
NeuroID/NeuroIDClass/NeuroID.swift
NeuroID/Utilities/NetworkMonitoringService.swift
SDKTest/DataStoreTests.swift
SDKTest/IntegrationHealthTests.swift
SDKTest/NIDEventTests.swift
SDKTest/NIDParamsCreatorTests.swift
SDKTest/NetworkMonitoringServiceTests.swift
SDKTest/NeuroIDClassTests.swift
SDKTest/NeuroIDTrackerTests.swift
SDKTest/SessionTests.swift
SDKTest/TouchEventsTests.swift
SDKTest/UtilFunctionsTests.swift

Note: Another PR will be coming that will stop collection of events based on network status, this PR is simply to capture the network status as it changes

ENG-7138 - Capture Network Status Event

---

NeuroID/NIDParamsCreator.swift
SDKTest/NIDParamsCreatorTests.swift
SDKTest/NeuroIDClassTests.swift

[ENG-8301](https://neuro-id.atlassian.net/browse/ENG-8301)
[ENG-8301]: https://neuro-id.atlassian.net/browse/ENG-8301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-8301-update random id generated with nid prefix

---

NeuroID/NeuroIDClass/Extensions/NIDLog.swift
NeuroID/NeuroIDClass/Extensions/NIDSend.swift
NeuroID/NeuroIDClass/Extensions/NIDSession.swift
NeuroID/SDKPreferences.swift
SDKTest/NIDEventTests.swift

(NeuroID Debug) Payload  
Payload Summary
ClientID: nid-09C352DF-F65E-4C8D-8851-B11B8C431F98
UserID:   sdfsdf
RegisteredUserID:   sdfsdf-registered
LinkedSiteID:  form_parks912
TabID:  nid777CD812A
Packet Number:  1
SDK Version:  5.ios-3.3.1
Screen Name:  login_screen
Event Count:  15

ENG-8355 - Add Payload Summary Logging

---

NeuroID.xcodeproj/project.pbxproj
NeuroID/Models/ApplicationMetaData.swift
NeuroID/NIDEvent.swift
NeuroID/NeuroIDClass/Extensions/NIDLog.swift
NeuroID/NeuroIDClass/Extensions/NIDSession.swift
NeuroID/NeuroIDClass/Extensions/NIDUser.swift
NeuroID/NeuroIDClass/NeuroID.swift
NeuroID/Utilities/NIDConfigService.swift
SDKTest/NeuroIDClassTests.swift

APPLICATION_METADATA - NO_TARGET - attrs=[versionName=2.3.1, versionNumber=3, packageName=Neuro-ID iOS SDK Storyboard Sandbox, applicationName=Neuro-ID iOS SDK Storyboard Sandbox]

ENG-8352 - Capture Application Metadata

---

NeuroID/Models/ConfigModels.swift
NeuroID/TrackerEvents/AppEvents.swift
NeuroID/Utilities/NIDConfigService.swift
SDKTest/NIDPerformanceTests.swift

Adds a remote back off config option for low memory events.

ENG-8302/Low memory back off remote config

---

NeuroID/NIDEvent.swift
NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
NeuroID/NeuroIDClass/Extensions/NIDListeners.swift
NeuroID/NeuroIDClass/Extensions/NIDLog.swift
NeuroID/NeuroIDClass/Extensions/NIDSession.swift
NeuroID/NeuroIDClass/NeuroID.swift
NeuroID/Utilities/NIDConfigService.swift
NeuroID/Utilities/NIDSamplingService.swift
NeuroID/Utilities/NetworkMonitoringService.swift
SDKTest/ConfigServiceTests.swift
SDKTest/SampleServiceTests.swift
SDKTest/Utils/MockConfigService.swift
SDKTest/Utils/MockDeviceSignalService.swift
SDKTest/Utils/NIDNetworkServiceTestImpl.swift

Dependent on the merge and release of https://github.com/Neuro-ID/neuroid-ios-advanced-device-sdk/pull/7/files

ENG-8305 - Config Non-Blocking

---

NeuroID/NeuroIDClass/NeuroID.swift
Podfile.lock

Updated to capture the bundleID `com.neuroid.sdksandbox.storyboard.dev`
Updated Event:
```
attrs=[
versionName=2.3.1,
versionNumber=3, 
packageName=com.neuroid.sdksandbox.storyboard.dev, 
applicationName=Neuro-ID iOS SDK Storyboard Sandbox
]
```

ENG-8352 - Capture Package Name

---

.github/workflows/version-update.yml

Adding link to release changes in Pre release PR body:
eg. Please review detailed release changes: [https://github.com/Neuro-ID/neuroid-ios-sdk/compare/v3.3.1...7e68d4de31c24d8b439219eb1f3aab0c6a2fad94](https://github.com/Neuro-ID/neuroid-ios-sdk/compare/v3.3.1...7e68d4de31c24d8b439219eb1f3aab0c6a2fad94)

ENG-8384 Add version release changes in pre-release PR

---

NeuroID/PrivacyInfo.xcprivacy

I picked this code because it seemed the most accurate. Other options listed here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

ENG-8566 - Update to specific Reason Code from Apple

---

Podfile
Podfile.lock

ENG-8873 update min version ios 13 and fix FPJS lib version to 2.6.0
Do I need to include the pod lock file as well?

ENG-8873 update min version ios 13 and fix FPJS lib version to 2.6.0

---

NeuroID.podspec
NeuroID/Info.plist

Reverts Neuro-ID/neuroid-ios-sdk#226

Revert "Release Version: 3.4.0"

---

NeuroID.xcodeproj/project.pbxproj
SDKTest/IdentifierServiceTests.swift
SDKTest/NeuroIDClassTests.swift
Source/NeuroID/Constants.swift
Source/NeuroID/Models/NIDEvent.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDRegistration.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDUser.swift
Source/NeuroID/NeuroIDClass/NeuroID.swift
Source/NeuroID/Services/IdentifierService.swift

Moved (https://github.com/Neuro-ID/neuroid-ios-sdk/pull/241) to here after large file changes would cause a merging nightmare

ENG-9224 - Identifier Service

---

Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift

add log event to indicate pause and resume attempt.

Eng 9802 add pause and resume event when calledsend

---

SDKTest/IdentifierServiceTests.swift
SDKTest/MultiAppFlowTests.swift
SDKTest/NeuroIDClassTests.swift
SDKTest/NeuroIDTrackerTests.swift
SDKTest/UtilFunctionsTests.swift

Disable certain tests due to un-reliability. Will Work on [ENG](https://neuro-id.atlassian.net/browse/ENG-10129) to fix tests ASAP so we can bring back these tests. These tests work locally but not on the server.

ENG-10130 disable tests

---

SDKTest/NeuroIDClassTests.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDRN.swift
Source/NeuroID/NeuroIDClass/NeuroID.swift

Pass ReactNative set advancedDeviceKey to the native NeuroID configuration.

ENG-10215 pass ReactNative set advancedDeviceKey to native

---

.github/workflows/test-sdk.yml
.github/workflows/version-update.yml

Putting the test action back in and will start working on a GitHub fix

ENG-10129 - Revert  Test Removal

---

NeuroID.xcodeproj/project.pbxproj
SDKTest/NeuroIDClass/NIDDataExtensionTests.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDClientSiteId.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDDataStore.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDForm.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDRegistration.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDSend.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDStatic.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDUser.swift
Source/NeuroID/NeuroIDClass/NeuroID.swift
Source/NeuroID/NeuroIDTracker.swift
Source/NeuroID/Services/EventStorageService.swift
Source/NeuroID/Services/NIDConfigService.swift
Source/NeuroID/Services/NetworkMonitoringService.swift
Source/NeuroID/TrackerClassExtensions/UIClassExtensions/UITextField.swift
Source/NeuroID/TrackerClassExtensions/UIClassExtensions/UITextView.swift
Source/NeuroID/TrackerClassExtensions/UIClassExtensions/UIViewController.swift
Source/NeuroID/TrackerClassExtensions/Utils.swift
Source/NeuroID/TrackerEvents/TouchEvents.swift

Functions Changed:
- NeuroID.saveEventToLocalDataStore
- NeuroID.saveEventToDataStore

ENG-10448 - Class Functions

---

SDKTest/NeuroIDClass/MultiAppFlowTests.swift
SDKTest/NeuroIDClass/NIDNewSessionTests.swift
SDKTest/NeuroIDClass/NIDSessionTests.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDScreen.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift
Source/NeuroID/NeuroIDClass/Extensions/NIDStatic.swift
Source/NeuroID/NeuroIDClass/NeuroID.swift

Updated:
- getNewADV
- captureADVEvent
- captureAdvancedDevice
- setScreenName
- createNIDSessionEvent
- createSession
- captureMobileMetadata
- clearSessionVariables

ENG-10473 - Static Functions Continued

---

Package.swift
Podfile
Podfile.lock

Update FPJS library 2.10.0. readme here:
https://dev.fingerprint.com/docs/changelog-ios-sdk#v2100
Tested in swift sandbox app. ADV device RID successfully received and passed to backend.

ENG-10593 update fpjs lib to 2.10.0
