Neuro-ID/neuroid-ios-sdk

- .github/workflows/github-actions-ios-staging.yml
- .github/workflows/github-actions-ios.yml
- .github/workflows/github-actions-version-check.yml
Divide the workflow on two jobs, so the notification system run on a linux (Ubuntu) machine
> [ENG-3954] - update the workflow with new version

- .github/workflows/ios-sandbox-deployment-prod.yml
Prod sandbox deploy was getting skipped since the step it was depending on was running on mutually exclusive condition.
> ENG-5919-edit prod sandbox deploy 

- NeuroID.xcodeproj/project.pbxproj
- NeuroID/NIDParamsCreator.swift
- NeuroID/NeuroIDClass/Extensions/NIDRN.swift
- NeuroID/NeuroIDClass/Extensions/NIDSend.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- NeuroID/NeuroIDClass/NeuroID.swift
- SDKTest/NeuroIDClassTests.swift
Added `isRN` bool var to the NeuroID Class
Added `setIsRN` method to mark isRN as true
Use `isRN` in the `getSDKVersion` method
Append a `isRN` key/value to the mobile metadata event
> ENG-6239 - RN sdk marker

- .github/workflows/ios-sandbox-deployment-dev.yml
- .github/workflows/ios-sandbox-deployment-prod.yml
Github slack notification action only runs on linux containers. Moved step to its own job.
> ENG-7490-moved slack notifications to another container

- .github/workflows/ios-sandbox-deployment-dev.yml
Updating the ios sdk development tag even on a release so that the version number is pointing to the latest version in the podspec file.
> ENG-7771-updating development tag even on release

- NeuroID/NeuroIDClass/Extensions/NIDSend.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- NeuroID/TrackerEvents/AppEvents.swift
- SDKTest/NeuroIDClassTests.swift
With automated testing @jeff-niemann  and I noticed that a packet could be sent with the wrong linkedSiteID because we send events which is async and then update the linkedSiteID. This is because of the race condition between sending the events and updating the static class variable. This PR introduces a callback for the posting of events to force the function to wait until the packet has been sent with the correct linkedSiteID.
> ENG-7938 - Post Events Race Condition Fix

- NeuroID/NeuroIDTracker.swift
- NeuroID/TrackerClassExtensions/Utils.swift
To provide more context, the previous usage of ctrls.view would force the view to load even if it wasn't ready, the new ctrls.viewIfLoaded will only load the view if its already been completely loaded. This fixes an issue where a customer can edit/reload a view while we are in the middle of loading it.
> ENG-8088 - Use viewIfLoaded

- NeuroID/Constants.swift
- NeuroID/NIDCallStatusObserver.swift
- NeuroID/NIDEvent.swift
- NeuroID/NeuroIDClass/Extensions/NIDLog.swift
- NeuroID/TrackerClassExtensions/Utils.swift
Call metadata would include the call type (incoming/outgoing) and call progress (ringing/answered/ended/onhold). 
Examples of the event:
["CALL_IN_PROGRESS - NO_TARGET - cp=Optional(\"false\") attrs=[type=outgoing, progress=ringing]"]
["CALL_IN_PROGRESS - NO_TARGET - cp=Optional(\"false\") attrs=[type=outgoing, progress=ended]"]
> ENG-8243-add call in progress event metadata

- NeuroID/Constants.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- NeuroID/NeuroIDClass/Extensions/NIDUser.swift
- NeuroID/NeuroIDClass/NeuroID.swift
- SDKTest/NeuroIDClassTests.swift
Refactoring the way Session ID origin event is sent to avoid sending duplicate SET_VARIABLE events. Creating an internal setUserID() method to allow a `userGenerated` flag. Updating the public setUsetID method to call the internal method with `userGenerated` flag defaulting to true.
> ENG-8323 Session ID origin logic setting refactor

- NeuroID/NeuroIDClass/Extensions/NIDSend.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- NeuroID/NeuroIDClass/Extensions/NIDUser.swift
- NeuroID/NeuroIDClass/NeuroID.swift
- NeuroID/Utilities/NIDConfigService.swift
- SDKTest/NeuroIDClassTests.swift
Add log events for the following events:
- set user id attempt - what was attempted to be set
- set registered user id attempt - what was attempted to be set
- set variable - put value in '' so to know its empty string or nil?
- tab id change/configure attempt or success? -_**(Note-only added tab reset log event and not retrieval. getTabId() is called after events are pulled from datastore and ready to be sent in post())**_
- start app flow log
- start and start session
- close session 
- any NeuroID error message record an internal log event
-Compare with Android [PR](https://github.com/Neuro-ID/neuroid-android-sdk/pull/337)
> ENG-8297 Log events and scrub user ID before logging

- NeuroID/NIDEvent.swift
- NeuroID/NeuroIDClass/Extensions/NIDRegistration.swift
- NeuroID/NeuroIDClass/NeuroID.swift
- NeuroID/NeuroIDTracker.swift
- NeuroID/TrackerClassExtensions/UIClassExtensions/UITableView.swift
- NeuroID/TrackerClassExtensions/UIClassExtensions/UIView.swift
- NeuroID/TrackerClassExtensions/UIClassExtensions/UIViewController.swift
- NeuroID/TrackerClassExtensions/Utils.swift
- SDKTest/NIDEventTests.swift
- SDKTest/NeuroIDTrackerTests.swift
- SDKTest/UIViewExtensionTests.swift
- SDKTest/UtilFunctionsTests.swift
From Top Controller:
```
top-screenHierarchy:BaseNavigation/UINavigation/UITextField
bot-screenHierarchy:/BaseNavigation/UINavigation/UITextField 
```
From Mid-Level Controller:
```
top-screenHierarchy:UINavigation/UITextField
bot-screenHierarchy:/BaseNavigation/UINavigation/UITextField  
```
> ENG-8365 - Update logic to get the screenHierarchy, add topDown and bottomUp path for verification

- NeuroID/NIDParamsCreator.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- SDKTest/NIDParamsCreatorTests.swift
- SDKTest/NeuroIDClassTests.swift
Removing `nid-` prefix from random generated id's like ClientID and tabID but keeping it for Session ID.
SessionId: nid-9EDAB3F8-7BB6-442C-9C59-7CD7D6B76A26
ClientID: 90D422EA-BD13-41F8-BB7C-A30144CF47FA
TabID: mobile-1B3037CF-4485-4940-B274-F017EE9D6909
> ENG-8455 removing nid prefix from all generated random id's except for Session ID

- NeuroID.podspec
- NeuroID/NIDParamsCreator.swift
- NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
- NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- NeuroID/NeuroIDClass/NeuroID.swift
- SDKTest/MultiAppFlowTests.swift
- SDKTest/NIDParamsCreatorTests.swift
- SDKTest/NeuroIDClassTests.swift
This will by default include all our AdvancedDevice functionality into our main SDK package instead of requiring a second library installation. The functionality can be used or ignored with the `isAdvancedDevice: Bool` parameter in the `configure` method. Additionally there are backend security checks for the given `clientKey` when an advanced device request is made to prevent unauthorized access.
> ENG-9192 - Combine ADV Library into Core

- NeuroID.xcodeproj/project.pbxproj
- SDKTest/BaseTestClass.swift
- SDKTest/ConfigServiceTests.swift
- SDKTest/DataStoreTests.swift
- SDKTest/IdentifierServiceTests.swift
- SDKTest/MultiAppFlowTests.swift
- SDKTest/NIDDataExtensionTests.swift
- SDKTest/NIDEventTests.swift
- SDKTest/NIDParamsCreatorTests.swift
- SDKTest/NeuroIDClassTests.swift
- SDKTest/NeuroIDTrackerTests.swift
- SDKTest/SessionTests.swift
- SDKTest/TouchEventsTests.swift
- SDKTest/UtilFunctionsTests.swift
- Source/NeuroID/DataStore.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDDataStore.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDSend.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- Source/NeuroID/NeuroIDClass/NeuroID.swift
- Source/NeuroID/NeuroIDTracker.swift
- Source/NeuroID/TrackerClassExtensions/UIClassExtensions/UIViewController.swift
- Source/NeuroID/TrackerClassExtensions/Utils.swift
- Source/NeuroID/TrackerEvents/AppEvents.swift
- Source/NeuroID/TrackerEvents/TouchEvents.swift
Make our Datastore a class instance instead of static. This is part 1 but I am breaking it up because the changes are so large. 
Future updates will make it so each testing group gets an individual instance of the class so that cross-tests will not impact each other.
> ENG-9249 - Datastore class refactor

- SDKTest/DataStoreTests.swift
- Source/NeuroID/Constants.swift
- Source/NeuroID/DataStore.swift
- Source/NeuroID/NIDMetadata.swift
- Source/NeuroID/NeuroIDClass/NeuroID.swift
Add the last install time in metadata. Below is a screenshot of the lastInstallTime in the metadata request body from WormHoly in the updated NeuroID iOS SDK running on the NeuroID SDK Swift sample app.
> ENG-9335 add last install time

- .github/workflows/version-update.yml
- SDKTest/NIDParamsCreatorTests.swift
- Scripts/update_version.sh
- Source/NeuroID/NIDParamsCreator.swift
Swift package builds will not show proper version. This PR addresses that. The github action will call update_version.sh to fill in the SDK version directly into the getSDKVersion() function at release time.
> Eng 9499 spm version fix

- .github/workflows/version-update.yml
fix formatting and file locations to make script work
you can see a run here: 
https://github.com/kishisaka-nid/neuroid-ios-sdk-version-fix/actions/runs/14371361930/job/40294894560
I am getting this error here. I am hopping it is just my fork and will not occur on the actual repo. 
```
Run git config --global user.email developer@neuro-id.com
git config --global user.email developer@neuro-id.com
git config --global user.name neuroid-developer
git checkout -b releases/[2](https://github.com/kishisaka-nid/neuroid-ios-sdk-version-fix/actions/runs/14371361930/job/40294894560#step:18:2).3.1_version_update
git status
set +e
git add NeuroID.podspec
git add Source/NeuroID/Info.plist
git add Source/NeuroID/NIDParamsCreator.swift
git commit -m "Update SDK to $PACKAGE_VERSION"
git tag …
```
> ENG-9499 fix formatting and file locations to make script work

- SDKTest/BaseTestClass.swift
- SDKTest/IdentifierServiceTests.swift
- SDKTest/MultiAppFlowTests.swift
- SDKTest/NeuroIDClassTests.swift
- SDKTest/UtilFunctionsTests.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDDataStore.swift
Ensure that only one FPJS call is run at any one time
Flush buffer immediately when certain event types are collected.
> ENG-10078 Ensure that only one FPJS call is run at any one time

- .github/workflows/version-update.yml
- SDKTest/Info.plist
- SDKUITest/Info.plist
Need to make versions align properly in all info.list and podspec files, then update the version_update.yml to commit the SDKTest and SDKUITest Info.plist files. 
The fastlane function update_project_version will find all versions in the project from plist and prospec files , take the lowest version and will update all found .plist files in project with CFBundleShortVersionString keys and .podspec files in project with s.version keys to this version number (major, minor, patch) + 1. The fastlane function get_project_version will then search all plist and podspec files and return the lowest version found which is why we need to fix all files to the same version and commit all plist and podspec files to fix the version which should fix the release process.
> ENG-10135 normalize all versions, commit test plists.

- Source/NeuroID/Models/ConfigModels.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDAdvancedDevice.swift
- Source/NeuroID/Services/NIDConfigService.swift
- Source/NeuroID/TrackerClassExtensions/Utils.swift
Pull and set FPJS ID cache expiration time from remote config. May need backend change as well to send this data over if not already in the config.
key is expected to be: advanced_cookie_expires and value is expected to be an int. 43200 seconds will be set as default
(NeuroID Debug) Event:  LOG - 1748547789758 - NO_TARGET - m=StartAppFlow attempt with siteID: form_parks912, sessionID:: null
(NeuroID Debug)   Retrieved remote config
(NeuroID Debug) Event:  CONFIG_CACHED - 1748547789813 - NO_TARGET -
> ENG-10128 add fpjs remote config param

- Source/NeuroID/Services/AdvancedDeviceService.swift
Currently, if a user enters empty string "" as a advancedDeviceKey parameter, it will be interpreted as a user entered key and the SDK will not retrieve an advanced device key from the server resulting in the advanced device RID call failure. 
To fix this we change empty strings to nil first, then we check for nil and either get the advanced device RID if we have a advanced device key or get the advanced device key from server then get the advanced device RID. Right now in ReactNative iOS and Android, we convert nil values to empty strings before sending them to configure which breaks iOS advanced device. 
iOS native use is working fine as long as users don't fill in the advancedDeviceKey parameter with empty strings.  This fix will allow users to set an empty string in advancedDeviceKey …
> ENG-10215 fix empty check, convert empty to nil for proper processing

- SDKTest/NeuroIDClass/NIDClientSiteIdTests.swift
- SDKTest/NeuroIDClass/NIDPerformanceTests.swift
- SDKTest/TestUtils/MockConfigService.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDClientSiteId.swift
Updated the getClientID tests to validate what was happening today, after I made those tests, I refactored the function so that it was easier to read and follow the logic.
Then I updated the tests for the rest of the functions in the NIDClientSiteID file
I removed the `isCollectionSite` function as it was not being used anywhere. I checked and it was used in the Sampling Service in the latest release but that class has since been deleted and refactored so this was dead code.
> ENG-10497 - Update ClientSiteID Tests

- SDKTest/NeuroIDClass/NIDRNTests.swift
- SDKTest/NeuroIDClass/NIDScreenTests.swift
- Source/NeuroID/NeuroIDClass/Extensions/NIDSession.swift
- Source/NeuroID/NeuroIDClass/NeuroID.swift
Updated the RN and Screen tests to be class based and scoped appropriately. 
Additionally updated the `captureMobileMetadata` and `captureApplicationMetaData` functions to use the class instance and service instead of the static one
> ENG-10497 - Update RN and Screen Tests
